# Generated by Django 5.1.3 on 2024-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60)),
                ('seat', models.PositiveIntegerField()),
                ('phone_number', models.IntegerField()),
                ('hour', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
                ('remark', models.TextField(max_length=200)),
                ('is_preorder', models.IntegerField(choices=[(1, '事前注文'), (2, 'お店で注文')])),
                ('is_eatin', models.IntegerField(choices=[(1, 'イートイン'), (2, 'テイクアウト')])),
            ],
        ),
    ]
