# Generated by Django 5.1.3 on 2024-12-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_date_time_reservation_start_reservation_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slot_index',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
