# Generated by Django 5.1.3 on 2024-12-09 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_slot_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
    ]
