# Generated by Django 5.1.3 on 2024-12-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='slot_index',
            field=models.IntegerField(choices=[(1, '1席'), (2, '2席'), (3, '3席'), (4, '4席'), (5, '5席'), (6, '6席'), (7, '7席'), (8, '8席')]),
        ),
    ]
