# Generated by Django 5.1.3 on 2024-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_slot_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(max_length=60, verbose_name='代表者名'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hour',
            field=models.PositiveIntegerField(verbose_name='お時間（最大2時間）'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_eatin',
            field=models.IntegerField(choices=[(1, 'イートイン'), (2, 'テイクアウト')], verbose_name='イートイン/テイクアウト'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_preorder',
            field=models.IntegerField(choices=[(1, '事前注文'), (2, 'お店で注文')], verbose_name='事前注文の有無'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.IntegerField(verbose_name='お電話番号'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='remark',
            field=models.TextField(max_length=200, verbose_name='備考欄'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='slot_index',
            field=models.IntegerField(choices=[(1, '1席'), (2, '2席'), (3, '3席'), (4, '4席'), (5, '5席'), (6, '6席'), (7, '7席'), (8, '8席')], verbose_name='席数'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(verbose_name='開始時間'),
        ),
    ]
