# Generated by Django 5.1.3 on 2024-12-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_slot_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
    ]
