# Generated by Django 5.1.3 on 2024-12-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='remark',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='備考欄'),
        ),
    ]
