# Generated by Django 5.1.3 on 2024-12-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('sort', models.IntegerField()),
            ],
        ),
    ]
