# Generated by Django 5.1.3 on 2024-12-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_seat_remove_reservation_slot_index_reservation_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seats',
        ),
        migrations.AddField(
            model_name='reservation',
            name='slot_index',
            field=models.IntegerField(choices=[(1, '1席'), (2, '2席'), (3, '3席'), (4, '4席'), (5, '5席'), (6, '6席'), (7, '7席'), (8, '8席')], default=1, verbose_name='お席'),
            preserve_default=False,
        ),
    ]
