# Generated by Django 5.1.3 on 2024-12-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_remove_reservation_seats_reservation_slot_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='slot_index',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_count',
            field=models.PositiveIntegerField(default=1, verbose_name='予約席数'),
        ),
    ]
