# Generated by Django 5.1.3 on 2024-12-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_comment_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=200, verbose_name='お知らせ内容'),
        ),
    ]
