# Generated by Django 5.1.3 on 2024-12-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='order_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
